apiVersion: v1
kind: Service
metadata:
  namespace: task1
  name: service1
spec:
  selector:
    name: deploy1
  ports:
    - name: name-of-service-port
      protocol: TCP
      port: 80
      targetPort: 3001